import { useState, useEffect } from "react";
import { decodeReportFromUrl, renderReportHtml, PDF_CSS } from "@/lib/report-export";

export default function ReportView() {
  const [title, setTitle]     = useState("");
  const [content, setContent] = useState("");
  const [error, setError]     = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [printed, setPrinted] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const d = params.get("d");
    if (!d) {
      setError("No report data in URL. Generate a share link from within the app.");
      setLoading(false);
      return;
    }
    decodeReportFromUrl(d)
      .then(({ title: t, content: c }) => {
        setTitle(t);
        setContent(c);
        document.title = `${t} — CryptoChainTrace`;
        setLoading(false);
      })
      .catch(() => {
        setError("Failed to decode report. The link may be malformed or too old.");
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a0c10] flex items-center justify-center">
        <span className="font-mono text-sm text-green-400 animate-pulse">Decoding report…</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#0a0c10] flex items-center justify-center p-8">
        <div className="text-center">
          <p className="font-mono text-xs text-orange-400 uppercase tracking-widest mb-3">CryptoChainTrace</p>
          <p className="font-mono text-sm text-red-400">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Top bar (hidden when printing) */}
      <div className="print:hidden sticky top-0 z-10 bg-[#0f1117] border-b border-orange-500/30 px-5 py-3 flex items-center justify-between gap-4 flex-wrap">
        <div>
          <p className="font-mono text-[10px] text-orange-400 uppercase tracking-widest">CryptoChainTrace — Shared Report</p>
          <p className="font-mono text-xs text-slate-400 mt-0.5">{title}</p>
        </div>
        <button
          onClick={() => { setPrinted(true); setTimeout(() => window.print(), 800); }}
          className={`flex items-center gap-2 text-xs font-mono font-bold px-4 py-2 rounded border transition-colors ${
            printed
              ? "border-green-500/50 text-green-400 bg-green-950/20"
              : "border-blue-500/40 text-blue-300 hover:bg-blue-950/30 hover:border-blue-400"
          }`}
        >
          {printed ? "✓ Printed" : "⬇ Save as PDF / Print"}
        </button>
      </div>

      {/* Print-only running header */}
      <div className="running-hdr">
        <div className="running-hdr-inner">
          <span>CryptoChainTrace — Blockchain Intelligence Platform</span>
          <span className="running-hdr-right">CONFIDENTIAL — LAW ENFORCEMENT USE</span>
        </div>
      </div>

      {/* Cover block (print only) */}
      <div className="hidden print:block cover">
        <div className="cover-badge">CryptoChainTrace — Blockchain Intelligence</div>
        <h1>{title}</h1>
        <div className="cover-grid">
          <span className="cover-label">Exported:</span>
          <span className="cover-val">{new Date().toISOString().replace("T", " ").slice(0, 19)} UTC</span>
          <span className="cover-label">Platform:</span>
          <span className="cover-val">CryptoChainTrace · cryptochaintrace.replit.app</span>
          <div className="cover-divider"></div>
          <span className="cover-label">Report Type:</span>
          <span className="cover-val">{title}</span>
          <span className="cover-label">Generated by:</span>
          <span className="cover-val">CryptoChainTrace Automated Analysis Engine</span>
          <div className="cover-classification">🔒 CONFIDENTIAL — LAW ENFORCEMENT / INVESTIGATIVE USE ONLY</div>
        </div>
      </div>

      {/* Report body — styled with same CSS as PDF export */}
      <div className="p-6 max-w-5xl mx-auto">
        <div
          className="report"
          dangerouslySetInnerHTML={{ __html: renderReportHtml(content) }}
        />
      </div>

      <style>{PDF_CSS}</style>
      <style>{`
        /* Screen-only overrides: tighten spacing and show running header */
        @media screen {
          .running-hdr { display: none !important; }
          .cover { display: none; }
          body { padding: 0; }
        }
        @media print {
          .print\\:hidden { display: none !important; }
          .hidden.print\\:block { display: block !important; }
        }
      `}</style>
    </div>
  );
}
