function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderReportHtml(content: string): string {
  return content
    .split("\n")
    .map((line) => {
      const esc = escHtml(line);
      const tr = line.trim();

      if (!tr) return '<div class="blank"></div>';

      if (line.startsWith("╔") || line.startsWith("╚"))
        return `<div class="title-border">${esc}</div>`;
      if (line.startsWith("║"))
        return `<div class="title-inner">${esc}</div>`;

      if (/^═+$/.test(tr))
        return '<div class="end-rule"></div>';

      // Named section headers (─── TIER 1...) vs plain rule lines
      if (tr.startsWith("─── "))
        return `<div class="section-sep">${esc}</div>`;
      if (/^─+$/.test(tr))
        return '<div class="thin-rule"></div>';

      if (line.includes("↳ Memo") || line.includes("↳ Destination Tag") ||
          line.includes("↳ Memos") || line.includes("↳ Destination Tags"))
        return `<div class="memo-line">${esc}</div>`;

      if (line.includes("◄ DAG OFFICIAL ENTITY") || line.includes("DAG OFFICIAL ENTITY"))
        return `<div class="dag-official-line">${esc}</div>`;

      if (line.includes("◄ OFFICIAL") || line.includes("COLDWALLET") ||
          line.includes("◄ EXCHANGE FLOW") || line.includes("◄ BRIDGE FLOW") ||
          line.includes("EXCHANGE / CUSTODIAL"))
        return `<div class="exchange-line">${esc}</div>`;

      if (line.includes("★ PRIVATE") || line.includes("PRIVATE WALLET CONNECTIONS"))
        return `<div class="private-line">${esc}</div>`;

      if (line.includes("⚠") || line.includes("COMMINGLING"))
        return `<div class="warn-line">${esc}</div>`;

      if (line.includes("HIGH RISK"))
        return `<div class="risk-high">${esc}</div>`;
      if (line.includes("MEDIUM RISK"))
        return `<div class="risk-med">${esc}</div>`;
      if (line.includes("LOW RISK") || line.includes("LOW-MEDIUM RISK"))
        return `<div class="risk-low">${esc}</div>`;

      // ── Hop-by-hop trail display ───────────────────────────────────────────
      // Target/shared endpoint addresses: "  addr  ← TARGET WALLET" / "← SHARED NODE"
      if (line.includes("← TARGET") || line.includes("← SHARED"))
        return `<div class="hop-endpoint-line">${esc}</div>`;
      // Hop arrow connector: "  ↓  Hop N"
      if (tr.startsWith("↓  Hop") || tr.startsWith("↓ Hop"))
        return `<div class="hop-arrow-line">${esc}</div>`;
      // "Full Trail" and "Transactions — Hop N" section labels
      if (line.includes("Full Trail") || line.includes("Transactions — Hop "))
        return `<div class="hop-tx-label">${esc}</div>`;
      // "trace X separately" investigation notes
      if (line.includes(": trace ") && line.includes("separately"))
        return `<div class="hop-note-line">${esc}</div>`;

      // ── Commingle report TX direction lines: ├─ [IN ]  From: ... → To: ... ──
      if (line.includes("[IN ]") && line.includes("From:"))
        return `<div class="tx-in">${esc}</div>`;
      if (line.includes("[OUT]") && line.includes("From:"))
        return `<div class="tx-out">${esc}</div>`;

      // Commingle TX detail lines: Amount / TX hash / Date (indented below direction)
      if ((line.includes("  Amount:") || line.includes("  TX    :") || line.includes("  Date  :")) &&
          !line.includes("TX Count") && !line.includes("TX Count"))
        return `<div class="tx-detail">${esc}</div>`;

      // ── Legacy TX lines (trail reports, wallet detail reports) ──
      const hasTxRef = line.includes("TX:") || line.includes("TA:");
      if (hasTxRef && (line.includes(" IN ") || (line.includes("+") && line.includes(" IN"))))
        return `<div class="tx-in">${esc}</div>`;
      if (hasTxRef && (line.includes("OUT") || line.includes("−")))
        return `<div class="tx-out">${esc}</div>`;

      // Numbered finding header lines: "  01. addr  [LABEL]"
      if (/^\s{2}\d{2}\.\s/.test(line))
        return `<div class="finding-header">${esc}</div>`;

      if (
        /^(Generated|Chain|Target|Comparison\s*\d|Primary|Total Wallets|Tracked Wallets|Depth|Min Tx|NOTE)\s*[:\|]/.test(tr) ||
        /^Wallet\s+\w/.test(tr)
      )
        return `<div class="meta-line">${esc}</div>`;

      if (tr.startsWith("Generated by CryptoChainTrace"))
        return `<div class="footer-line">${esc}</div>`;

      return `<div class="line">${esc}</div>`;
    })
    .join("");
}

const PDF_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }

  @media print {
    @page {
      margin: 24mm 18mm 22mm;
      size: A4;
      @top-right { content: counter(page); font-family: Arial, sans-serif; font-size: 7pt; color: #888; }
    }
    body { padding: 0; }
    .no-print { display: none !important; }
    .running-hdr { display: block !important; }

    /* Section headers never stranded at bottom of page */
    .section-sep { page-break-after: avoid; page-break-before: auto; }
    .title-border, .title-inner { page-break-inside: avoid; }
    .cover { page-break-inside: avoid; page-break-after: always; }

    /* Keep TX direction + all details + memo together */
    .tx-in, .tx-out { page-break-inside: avoid; page-break-after: avoid; }
    .tx-detail { page-break-inside: avoid; page-break-before: avoid; page-break-after: avoid; }
    .memo-line { page-break-inside: avoid; page-break-before: avoid; }

    /* Keep labeled section openers with first finding */
    .private-line, .exchange-line, .dag-official-line, .warn-line { page-break-after: avoid; }
    /* Hop trail blocks */
    .hop-tx-label { page-break-after: avoid; }
    .hop-endpoint-line, .hop-arrow-line { page-break-inside: avoid; page-break-after: avoid; }
    /* Finding headers always lead their block */
    .finding-header { page-break-after: avoid; }
    .meta-line { page-break-after: avoid; }
    .end-rule, .thin-rule { page-break-before: avoid; }
  }

  body {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    line-height: 1.65;
    color: #111;
    background: #fff;
    padding: 0 2mm;
    counter-reset: page;
  }

  .running-hdr {
    display: none;
    position: fixed;
    top: -20mm;
    left: 0; right: 0;
    border-bottom: 0.5pt solid #bbb;
    padding-bottom: 4pt;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 7pt;
    color: #777;
  }
  .running-hdr-inner {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .running-hdr-right { font-style: italic; }

  /* Save-as-PDF bar (screen only) */
  .save-bar {
    position: sticky;
    top: 0;
    background: #0f172a;
    color: #e2e8f0;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 11pt;
    padding: 10pt 18pt;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12pt;
    z-index: 100;
    border-bottom: 2pt solid #3b82f6;
    box-shadow: 0 2pt 8pt rgba(59,130,246,0.2);
  }
  .save-bar-text { font-size: 9pt; color: #94a3b8; }
  .save-btn {
    background: #3b82f6;
    color: #fff;
    border: none;
    border-radius: 4pt;
    padding: 7pt 20pt;
    font-size: 10pt;
    font-weight: bold;
    cursor: pointer;
    letter-spacing: 0.04em;
    white-space: nowrap;
    transition: background 0.15s;
  }
  .save-btn:hover { background: #2563eb; }

  /* ── Cover block ─────────────────────────────────────────────────────────── */
  .cover {
    border: 2pt solid #1e293b;
    border-top: 6pt solid #1e3a5f;
    padding: 20pt 24pt 18pt;
    margin-bottom: 32pt;
    margin-top: 14pt;
    background: #fafbfc;
  }
  .cover-badge {
    display: inline-block;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 7pt;
    font-weight: bold;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    background: #1e3a5f;
    color: #fff;
    padding: 2pt 7pt;
    border-radius: 2pt;
    margin-bottom: 10pt;
  }
  .cover h1 {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 15pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #0f172a;
    margin-bottom: 16pt;
    border-bottom: 1pt solid #cbd5e1;
    padding-bottom: 10pt;
  }
  .cover-grid {
    display: grid;
    grid-template-columns: 115pt 1fr;
    gap: 4pt 0;
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    line-height: 1.6;
  }
  .cover-label { font-weight: bold; color: #0f172a; }
  .cover-val { color: #1e293b; word-break: break-all; }
  .cover-divider { grid-column: 1/-1; height: 1pt; background: #e2e8f0; margin: 8pt 0; }
  .cover-classification {
    grid-column: 1/-1;
    margin-top: 10pt;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 7.5pt;
    color: #dc2626;
    font-weight: bold;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    border-top: 0.5pt solid #fca5a5;
    padding-top: 6pt;
  }

  /* ── Base line styles ────────────────────────────────────────────────────── */
  .line, .blank, .meta-line, .footer-line,
  .title-border, .title-inner, .section-sep, .end-rule, .thin-rule,
  .memo-line, .warn-line, .exchange-line, .private-line, .dag-official-line,
  .hop-endpoint-line, .hop-arrow-line, .hop-tx-label, .hop-note-line, .finding-header,
  .tx-in, .tx-out, .tx-detail, .risk-high, .risk-med, .risk-low {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.65;
  }

  .blank { height: 7pt; }
  .title-border, .title-inner { font-size: 10.5pt; font-weight: bold; letter-spacing: 0.01em; }
  .title-border { margin-top: 8pt; }

  /* ── Section separator: dark navy band ──────────────────────────────────── */
  .section-sep {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
    font-size: 8.5pt;
    color: #fff;
    background: #1e3a5f;
    padding: 5pt 10pt;
    margin-top: 20pt;
    margin-bottom: 4pt;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    white-space: pre-wrap;
  }
  .thin-rule { height: 0.75pt; background: #d1d5db; margin: 5pt 0; }
  .end-rule   { height: 2pt; background: #1e293b; margin: 22pt 0 12pt; }

  /* ── TX direction lines ──────────────────────────────────────────────────── */
  .tx-in {
    color: #064e3b;
    font-weight: bold;
    font-size: 9.5pt;
    background: #ecfdf5;
    border-left: 4pt solid #059669;
    padding: 3pt 7pt;
    margin-top: 7pt;
    margin-bottom: 0;
    white-space: pre-wrap;
    word-break: break-all;
  }
  .tx-out {
    color: #7f1d1d;
    font-weight: bold;
    font-size: 9.5pt;
    background: #fff1f2;
    border-left: 4pt solid #dc2626;
    padding: 3pt 7pt;
    margin-top: 7pt;
    margin-bottom: 0;
    white-space: pre-wrap;
    word-break: break-all;
  }

  /* TX detail lines (Amount / TX / Date) */
  .tx-detail {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.55;
    background: #f0fdf4;
    border-left: 4pt solid #a7f3d0;
    padding: 1pt 7pt;
    color: #1a1a1a;
    margin-bottom: 0;
  }
  .tx-out + .tx-detail { background: #fff5f5; border-left-color: #fecaca; }
  .tx-detail + .tx-detail { border-left-color: #d1d5db; background: #f9fafb; }

  .memo-line {
    background: #fffbeb;
    border-left: 4pt solid #d97706;
    padding: 2pt 7pt;
    font-weight: bold;
    color: #451a03;
    margin: 1pt 0;
  }
  .exchange-line {
    background: #eff6ff;
    border-left: 4pt solid #2563eb;
    padding: 3pt 9pt;
    font-weight: bold;
    color: #1e3a8a;
    margin: 3pt 0;
  }
  .private-line {
    background: #f0fdf4;
    border-left: 4pt solid #16a34a;
    padding: 3pt 9pt;
    font-weight: bold;
    color: #14532d;
    margin: 3pt 0;
  }
  .dag-official-line {
    background: #fff7ed;
    border-left: 4pt solid #ea580c;
    padding: 3pt 9pt;
    font-weight: bold;
    color: #431407;
    margin: 3pt 0;
  }

  /* ── Hop-by-hop trail display ────────────────────────────────────────────── */
  .hop-tx-label {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 8pt;
    white-space: pre-wrap;
    word-break: break-all;
    padding: 5pt 8pt 2pt;
    font-weight: bold;
    color: #1e3a5f;
    margin-top: 8pt;
    letter-spacing: 0.02em;
  }
  .hop-endpoint-line {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    white-space: pre-wrap;
    word-break: break-all;
    background: #eef2ff;
    border-left: 3pt solid #6366f1;
    padding: 2pt 9pt;
    font-weight: bold;
    color: #1e1b4b;
    line-height: 1.6;
  }
  .hop-arrow-line {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8pt;
    white-space: pre-wrap;
    color: #7c3aed;
    padding: 1pt 9pt;
    font-style: italic;
  }
  .hop-note-line {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8pt;
    white-space: pre-wrap;
    word-break: break-all;
    color: #6b7280;
    font-style: italic;
    padding: 1pt 9pt;
    border-left: 2pt solid #e5e7eb;
  }

  /* ── Numbered finding headers: "  01. addr  [LABEL]" ──────────────────────── */
  .finding-header {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.65;
    margin-top: 14pt;
    padding: 4pt 8pt;
    font-weight: bold;
    color: #0f172a;
    border-left: 3pt solid #94a3b8;
    border-bottom: 0.75pt solid #e5e7eb;
    background: #f8fafc;
  }

  .warn-line {
    background: #fffbeb;
    border-left: 4pt solid #d97706;
    padding: 3pt 9pt;
    font-weight: bold;
    color: #78350f;
    margin: 3pt 0;
  }

  .risk-high { font-weight: bold; color: #7f1d1d; font-size: 9.5pt; }
  .risk-med  { font-weight: bold; color: #92400e; font-size: 9.5pt; }
  .risk-low  { font-weight: bold; color: #14532d; font-size: 9.5pt; }

  .meta-line   { color: #475569; font-size: 8.5pt; }
  .footer-line { color: #94a3b8; font-size: 8pt; margin-top: 12pt; font-style: italic; }
`;

export function exportAsPdf(title: string, content: string): void {
  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups for this site, then click Export PDF again.");
    return;
  }
  const now = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const body = renderReportHtml(content);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escHtml(title)}</title>
<style>${PDF_CSS}</style>
</head>
<body>

<div class="running-hdr">
  <div class="running-hdr-inner">
    <span>CryptoChainTrace &mdash; Blockchain Intelligence Platform</span>
    <span class="running-hdr-right">CONFIDENTIAL &mdash; LAW ENFORCEMENT USE</span>
  </div>
</div>

<div class="save-bar no-print">
  <div>
    <div style="font-weight:bold;font-size:11pt;">CryptoChainTrace &mdash; ${escHtml(title)}</div>
    <div class="save-bar-text">Click &ldquo;Save as PDF&rdquo; in the print dialog that opens</div>
  </div>
  <button class="save-btn" onclick="window.print()">&#8964;&nbsp; Save as PDF</button>
</div>

<div class="cover">
  <div class="cover-badge">CryptoChainTrace &mdash; Blockchain Intelligence</div>
  <h1>${escHtml(title)}</h1>
  <div class="cover-grid">
    <span class="cover-label">Exported:</span>
    <span class="cover-val">${escHtml(now)}</span>
    <span class="cover-label">Platform:</span>
    <span class="cover-val">CryptoChainTrace &middot; cryptochaintrace.replit.app</span>
    <div class="cover-divider"></div>
    <span class="cover-label">Report Type:</span>
    <span class="cover-val">${escHtml(title)}</span>
    <span class="cover-label">Generated by:</span>
    <span class="cover-val">CryptoChainTrace Automated Analysis Engine</span>
    <div class="cover-classification">&#x1F512; CONFIDENTIAL &mdash; LAW ENFORCEMENT / INVESTIGATIVE USE ONLY</div>
  </div>
</div>

<div class="report">${body}</div>

<script>
  window.addEventListener('load', function () {
    setTimeout(function () { window.print(); }, 400);
  });
</script>
</body>
</html>`;

  w.document.write(html);
  w.document.close();
}

export function exportAsJson(filename: string, data: unknown): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function reportFilename(title: string, ext: "pdf" | "json"): string {
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/, "");
  return `${slug}-${dateStr}.${ext}`;
}

// ── URL-based report sharing ──────────────────────────────────────────────────

export async function encodeReportForUrl(title: string, content: string): Promise<string> {
  const json = JSON.stringify({ title, content });
  const bytes = new TextEncoder().encode(json);
  const cs = new CompressionStream("gzip");
  const writer = cs.writable.getWriter();
  writer.write(bytes);
  writer.close();
  const buf = await new Response(cs.readable).arrayBuffer();
  const b64 = btoa(String.fromCharCode(...new Uint8Array(buf)));
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

export async function decodeReportFromUrl(encoded: string): Promise<{ title: string; content: string }> {
  const b64 = encoded.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  const ds = new DecompressionStream("gzip");
  const writer = ds.writable.getWriter();
  writer.write(bytes);
  writer.close();
  const buf = await new Response(ds.readable).arrayBuffer();
  return JSON.parse(new TextDecoder().decode(buf));
}
