function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderReportHtml(content: string): string {
  return content
    .split("\n")
    .map((line) => {
      const esc = escHtml(line);
      const tr = line.trim();

      if (!tr) return '<div class="blank"></div>';

      if (line.startsWith("╔") || line.startsWith("╚"))
        return `<div class="title-border">${esc}</div>`;
      if (line.startsWith("║"))
        return `<div class="title-inner">${esc}</div>`;

      if (/^═+$/.test(tr))
        return '<div class="end-rule"></div>';

      // Named section headers (─── TIER 1...) vs plain rule lines
      if (tr.startsWith("─── "))
        return `<div class="section-sep">${esc}</div>`;
      if (/^─+$/.test(tr))
        return '<div class="thin-rule"></div>';

      if (line.includes("↳ Memo") || line.includes("↳ Destination Tag") ||
          line.includes("↳ Memos") || line.includes("↳ Destination Tags"))
        return `<div class="memo-line">${esc}</div>`;

      if (line.includes("◄ DAG OFFICIAL ENTITY") || line.includes("DAG OFFICIAL ENTITY"))
        return `<div class="dag-official-line">${esc}</div>`;

      if (line.includes("◄ OFFICIAL") || line.includes("COLDWALLET") ||
          line.includes("◄ EXCHANGE FLOW") || line.includes("EXCHANGE / CUSTODIAL"))
        return `<div class="exchange-line">${esc}</div>`;

      if (line.includes("★ PRIVATE") || line.includes("PRIVATE WALLET CONNECTIONS"))
        return `<div class="private-line">${esc}</div>`;

      if (line.includes("⚠") || line.includes("COMMINGLING"))
        return `<div class="warn-line">${esc}</div>`;

      if (line.includes("HIGH RISK"))
        return `<div class="risk-high">${esc}</div>`;
      if (line.includes("MEDIUM RISK"))
        return `<div class="risk-med">${esc}</div>`;
      if (line.includes("LOW RISK") || line.includes("LOW-MEDIUM RISK"))
        return `<div class="risk-low">${esc}</div>`;

      // ── Commingle report TX direction lines: ├─ [IN ]  From: ... → To: ... ──
      if (line.includes("[IN ]") && line.includes("From:"))
        return `<div class="tx-in">${esc}</div>`;
      if (line.includes("[OUT]") && line.includes("From:"))
        return `<div class="tx-out">${esc}</div>`;

      // Commingle TX detail lines: Amount / TX hash / Date (indented below direction)
      if ((line.includes("  Amount:") || line.includes("  TX    :") || line.includes("  Date  :")) &&
          !line.includes("TX Count") && !line.includes("TX Count"))
        return `<div class="tx-detail">${esc}</div>`;

      // ── Legacy TX lines (trail reports, wallet detail reports) ──
      const hasTxRef = line.includes("TX:") || line.includes("TA:");
      if (hasTxRef && (line.includes(" IN ") || (line.includes("+") && line.includes(" IN"))))
        return `<div class="tx-in">${esc}</div>`;
      if (hasTxRef && (line.includes("OUT") || line.includes("−")))
        return `<div class="tx-out">${esc}</div>`;

      if (/^(Generated|Chain|Target|Comparison\s*\d|Depth|Min Tx)\s*[:\|]/.test(tr))
        return `<div class="meta-line">${esc}</div>`;

      if (tr.startsWith("Generated by CryptoChainTrace"))
        return `<div class="footer-line">${esc}</div>`;

      return `<div class="line">${esc}</div>`;
    })
    .join("");
}

const PDF_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }

  @media print {
    @page { margin: 22mm 18mm 22mm; size: A4; }
    body { padding: 0; }
    .no-print { display: none !important; }
    .running-hdr { display: block !important; }

    /* Section header should not be orphaned at bottom of page */
    .section-sep { page-break-after: avoid; page-break-before: auto; }
    .title-border, .title-inner { page-break-inside: avoid; }
    .cover { page-break-inside: avoid; page-break-after: always; }

    /* Keep TX direction line + all its detail + memo lines together */
    .tx-in, .tx-out { page-break-inside: avoid; page-break-after: avoid; }
    .tx-detail { page-break-inside: avoid; page-break-before: avoid; page-break-after: avoid; }
    .memo-line { page-break-inside: avoid; page-break-before: avoid; }

    /* Keep private/exchange/dag-official section headers with the first finding below */
    .private-line, .exchange-line, .dag-official-line { page-break-after: avoid; }
    .end-rule, .thin-rule { page-break-before: avoid; }
  }

  body {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    line-height: 1.7;
    color: #111;
    background: #fff;
    padding: 0 2mm;
  }

  .running-hdr {
    display: none;
    position: fixed;
    top: -18mm;
    left: 0; right: 0;
    border-bottom: 0.75pt solid #999;
    padding-bottom: 3pt;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 7pt;
    color: #666;
  }
  .running-hdr-inner { display: flex; justify-content: space-between; }

  /* Save-as-PDF bar (screen only) */
  .save-bar {
    position: sticky;
    top: 0;
    background: #1a1a2e;
    color: #e2e8f0;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 11pt;
    padding: 10pt 16pt;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12pt;
    z-index: 100;
    border-bottom: 2pt solid #3b82f6;
  }
  .save-bar-text { font-size: 9pt; color: #94a3b8; }
  .save-btn {
    background: #3b82f6;
    color: #fff;
    border: none;
    border-radius: 4pt;
    padding: 7pt 18pt;
    font-size: 10pt;
    font-weight: bold;
    cursor: pointer;
    letter-spacing: 0.03em;
    white-space: nowrap;
  }
  .save-btn:hover { background: #2563eb; }

  /* Cover block */
  .cover {
    border: 2pt solid #111;
    padding: 18pt 22pt;
    margin-bottom: 30pt;
    margin-top: 16pt;
  }
  .cover h1 {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 14pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #000;
    margin-bottom: 14pt;
    border-bottom: 1.5pt solid #bbb;
    padding-bottom: 10pt;
  }
  .cover-grid {
    display: grid;
    grid-template-columns: 105pt 1fr;
    gap: 5pt 0;
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
  }
  .cover-label { font-weight: bold; color: #000; }
  .cover-val { color: #222; word-break: break-all; }

  /* Base line styles */
  .line, .blank, .meta-line, .footer-line,
  .title-border, .title-inner, .section-sep, .end-rule, .thin-rule,
  .memo-line, .warn-line, .exchange-line, .private-line, .dag-official-line,
  .tx-in, .tx-out, .tx-detail, .risk-high, .risk-med, .risk-low {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.7;
  }

  .blank { height: 8pt; }
  .title-border, .title-inner { font-size: 10pt; font-weight: bold; }
  .title-border { margin-top: 6pt; }

  /* Section separator: dark navy band with white text — clearly marks each tier */
  .section-sep {
    font-family: 'Courier New', Courier, monospace;
    font-weight: bold;
    font-size: 9.5pt;
    color: #fff;
    background: #1e3a5f;
    padding: 5pt 8pt;
    margin-top: 18pt;
    margin-bottom: 6pt;
    letter-spacing: 0.02em;
    white-space: pre-wrap;
  }
  .thin-rule { height: 1pt; background: #ccc; margin: 4pt 0; }
  .end-rule   { height: 2pt; background: #333; margin: 20pt 0 10pt; }

  /* TX direction line — the most important line: shows who sent to whom */
  .tx-in {
    color: #0a4a0a;
    font-weight: bold;
    font-size: 9.5pt;
    background: #ecfdf5;
    border-left: 4pt solid #16a34a;
    padding: 3pt 6pt;
    margin-top: 6pt;
    margin-bottom: 0;
    white-space: pre-wrap;
    word-break: break-all;
  }
  .tx-out {
    color: #7a0000;
    font-weight: bold;
    font-size: 9.5pt;
    background: #fff1f1;
    border-left: 4pt solid #dc2626;
    padding: 3pt 6pt;
    margin-top: 6pt;
    margin-bottom: 0;
    white-space: pre-wrap;
    word-break: break-all;
  }

  /* TX detail lines: Amount / TX hash / Date (directly below the direction line) */
  .tx-detail {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.6;
    background: #f6fef9;
    border-left: 4pt solid #bbf7d0;
    padding: 1pt 6pt;
    color: #1a1a1a;
    margin-bottom: 0;
  }
  /* OUT TX detail gets matching reddish tint */
  .tx-out + .tx-detail,
  .tx-detail + .tx-detail {
    background: inherit;
  }

  .memo-line {
    background: #fffbe6;
    border-left: 4pt solid #b8860b;
    padding: 2pt 6pt;
    font-weight: bold;
    color: #4a2e00;
    margin: 1pt 0;
  }
  .exchange-line {
    background: #e8f4fd;
    border-left: 4pt solid #1a6fa0;
    padding: 3pt 8pt;
    font-weight: bold;
    color: #0c2f4a;
    margin: 3pt 0;
  }
  .private-line {
    background: #e8f5e9;
    border-left: 4pt solid #2e7d32;
    padding: 3pt 8pt;
    font-weight: bold;
    color: #1b3a1d;
    margin: 3pt 0;
  }
  /* DAG official entity lines — orange, distinct from exchange (blue) and private (green) */
  .dag-official-line {
    background: #fff7ed;
    border-left: 4pt solid #ea580c;
    padding: 3pt 8pt;
    font-weight: bold;
    color: #431407;
    margin: 3pt 0;
  }
  .warn-line {
    background: #fff3cd;
    border-left: 4pt solid #d97706;
    padding: 3pt 8pt;
    font-weight: bold;
    color: #6b3800;
    margin: 3pt 0;
  }

  .risk-high { font-weight: bold; color: #8b0000; font-size: 9.5pt; }
  .risk-med  { font-weight: bold; color: #b45309; font-size: 9.5pt; }
  .risk-low  { font-weight: bold; color: #166534; font-size: 9.5pt; }

  .meta-line   { color: #444; }
  .footer-line { color: #999; font-size: 8pt; margin-top: 10pt; }
`;

export function exportAsPdf(title: string, content: string): void {
  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups for this site, then click Export PDF again.");
    return;
  }
  const now = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const body = renderReportHtml(content);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escHtml(title)}</title>
<style>${PDF_CSS}</style>
</head>
<body>

<div class="running-hdr">
  <div class="running-hdr-inner">
    <span>CryptoChainTrace — Blockchain Intelligence Platform</span>
    <span>CONFIDENTIAL — LAW ENFORCEMENT USE</span>
  </div>
</div>

<div class="save-bar no-print">
  <div>
    <div style="font-weight:bold;font-size:11pt;">CryptoChainTrace — ${escHtml(title)}</div>
    <div class="save-bar-text">Click the button → choose "Save as PDF" in the print dialog</div>
  </div>
  <button class="save-btn" onclick="window.print()">&#8964; Save as PDF</button>
</div>

<div class="cover">
  <h1>${escHtml(title)}</h1>
  <div class="cover-grid">
    <span class="cover-label">Exported:</span>
    <span class="cover-val">${escHtml(now)}</span>
    <span class="cover-label">Platform:</span>
    <span class="cover-val">CryptoChainTrace &middot; cryptochaintrace.replit.app</span>
    <span class="cover-label">Classification:</span>
    <span class="cover-val">Confidential — Law Enforcement / Investigative Reference</span>
  </div>
</div>

<div class="report">${body}</div>

<script>
  window.addEventListener('load', function () {
    setTimeout(function () { window.print(); }, 400);
  });
</script>
</body>
</html>`;

  w.document.write(html);
  w.document.close();
}

export function exportAsJson(filename: string, data: unknown): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function reportFilename(title: string, ext: "pdf" | "json"): string {
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/, "");
  return `${slug}-${dateStr}.${ext}`;
}

// ── URL-based report sharing ──────────────────────────────────────────────────

export async function encodeReportForUrl(title: string, content: string): Promise<string> {
  const json = JSON.stringify({ title, content });
  const bytes = new TextEncoder().encode(json);
  const cs = new CompressionStream("gzip");
  const writer = cs.writable.getWriter();
  writer.write(bytes);
  writer.close();
  const buf = await new Response(cs.readable).arrayBuffer();
  const b64 = btoa(String.fromCharCode(...new Uint8Array(buf)));
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

export async function decodeReportFromUrl(encoded: string): Promise<{ title: string; content: string }> {
  const b64 = encoded.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  const ds = new DecompressionStream("gzip");
  const writer = ds.writable.getWriter();
  writer.write(bytes);
  writer.close();
  const buf = await new Response(ds.readable).arrayBuffer();
  return JSON.parse(new TextDecoder().decode(buf));
}
