function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderReportHtml(content: string): string {
  return content
    .split("\n")
    .map((line) => {
      const esc = escHtml(line);
      const tr = line.trim();

      if (!tr) return '<div class="blank"></div>';

      if (line.startsWith("╔") || line.startsWith("╚"))
        return `<div class="title-border">${esc}</div>`;
      if (line.startsWith("║"))
        return `<div class="title-inner">${esc}</div>`;

      if (/^═+$/.test(tr))
        return '<div class="end-rule"></div>';

      if (tr.startsWith("─── ") || /^─+$/.test(tr))
        return `<div class="section-sep">${esc}</div>`;

      if (line.includes("↳ Memo") || line.includes("↳ Destination Tag") ||
          line.includes("↳ Memos") || line.includes("↳ Destination Tags"))
        return `<div class="memo-line">${esc}</div>`;

      if (line.includes("◄ OFFICIAL") || line.includes("COLDWALLET"))
        return `<div class="exchange-line">${esc}</div>`;

      if (line.includes("⚠") || line.includes("COMMINGLING"))
        return `<div class="warn-line">${esc}</div>`;

      if (line.includes("HIGH RISK"))
        return `<div class="risk-high">${esc}</div>`;
      if (line.includes("MEDIUM RISK"))
        return `<div class="risk-med">${esc}</div>`;
      if (line.includes("LOW RISK"))
        return `<div class="risk-low">${esc}</div>`;

      if (line.includes(" IN ") && line.includes("TA:"))
        return `<div class="tx-in">${esc}</div>`;
      if (line.includes("OUT") && line.includes("TA:"))
        return `<div class="tx-out">${esc}</div>`;

      if (/^(Generated|Chain|Target|Comparison\s*\d|Depth)\s*[:\|]/.test(tr))
        return `<div class="meta-line">${esc}</div>`;

      if (tr.startsWith("Generated by CryptoChainTrace"))
        return `<div class="footer-line">${esc}</div>`;

      return `<div class="line">${esc}</div>`;
    })
    .join("");
}

export function exportAsPdf(title: string, content: string): void {
  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups for this site, then click Export PDF again.");
    return;
  }
  const now = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const body = renderReportHtml(content);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escHtml(title)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }

  @media print {
    @page { margin: 22mm 18mm 18mm; size: A4; }
    body { padding: 0; }
    .no-print { display: none !important; }
    .running-hdr { display: block !important; }
    .section-sep { page-break-after: avoid; }
    .title-border, .title-inner { page-break-inside: avoid; }
    .tx-in, .tx-out, .memo-line, .exchange-line, .warn-line {
      page-break-inside: avoid;
    }
  }

  body {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    line-height: 1.55;
    color: #111;
    background: #fff;
    padding: 0 2mm;
  }

  /* Fixed header printed on every page */
  .running-hdr {
    display: none;
    position: fixed;
    top: -18mm;
    left: 0; right: 0;
    border-bottom: 0.75pt solid #999;
    padding-bottom: 3pt;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 7pt;
    color: #666;
  }
  .running-hdr-inner {
    display: flex;
    justify-content: space-between;
  }

  /* Cover block */
  .cover {
    border: 2pt solid #111;
    padding: 14pt 18pt 14pt;
    margin-bottom: 22pt;
    page-break-inside: avoid;
  }
  .cover h1 {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 13.5pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #000;
    margin-bottom: 10pt;
  }
  .cover-grid {
    display: grid;
    grid-template-columns: 90pt 1fr;
    gap: 3pt 0;
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
  }
  .cover-label {
    font-weight: bold;
    color: #000;
  }
  .cover-val {
    color: #222;
    word-break: break-all;
  }

  /* Base line styles */
  .line, .blank, .meta-line, .footer-line,
  .title-border, .title-inner, .section-sep, .end-rule,
  .memo-line, .warn-line, .exchange-line,
  .tx-in, .tx-out, .risk-high, .risk-med, .risk-low {
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    white-space: pre-wrap;
    word-break: break-all;
    line-height: 1.5;
  }

  .blank { height: 5pt; }

  /* Title box */
  .title-border, .title-inner {
    font-size: 9.5pt;
    font-weight: bold;
  }
  .title-border { margin-top: 2pt; }

  /* Section separator */
  .section-sep {
    font-weight: bold;
    font-size: 9pt;
    color: #111;
    margin-top: 10pt;
    padding-top: 4pt;
    border-top: 1pt solid #bbb;
  }

  /* End rule */
  .end-rule {
    height: 1.5pt;
    background: #333;
    margin: 14pt 0 6pt;
  }

  /* Memo / Destination Tag — gold highlight */
  .memo-line {
    background: #fffbe6;
    border-left: 3.5pt solid #b8860b;
    padding-left: 6pt;
    font-weight: bold;
    color: #4a2e00;
    margin: 1.5pt 0;
  }

  /* Exchange / official wallet — blue highlight */
  .exchange-line {
    background: #e8f4fd;
    border-left: 3.5pt solid #1a6fa0;
    padding-left: 6pt;
    font-weight: bold;
    color: #0c2f4a;
    margin: 1.5pt 0;
  }

  /* Commingling / warning — amber highlight */
  .warn-line {
    background: #fff3cd;
    border-left: 3.5pt solid #d97706;
    padding-left: 6pt;
    font-weight: bold;
    color: #6b3800;
    margin: 1.5pt 0;
  }

  /* Risk assessment labels */
  .risk-high { font-weight: bold; color: #8b0000; font-size: 9pt; }
  .risk-med  { font-weight: bold; color: #b45309; font-size: 9pt; }
  .risk-low  { font-weight: bold; color: #166534; font-size: 9pt; }

  /* IN / OUT transaction lines */
  .tx-in  { color: #145a14; font-weight: bold; }
  .tx-out { color: #8b0000; font-weight: bold; }

  /* Meta / footer */
  .meta-line   { color: #444; }
  .footer-line { color: #999; font-size: 7.5pt; margin-top: 8pt; }
</style>
</head>
<body>

<div class="running-hdr">
  <div class="running-hdr-inner">
    <span>CryptoChainTrace — Blockchain Intelligence Platform</span>
    <span>CONFIDENTIAL — LAW ENFORCEMENT USE</span>
  </div>
</div>

<div class="cover">
  <h1>${escHtml(title)}</h1>
  <div class="cover-grid">
    <span class="cover-label">Exported:</span>
    <span class="cover-val">${escHtml(now)}</span>
    <span class="cover-label">Platform:</span>
    <span class="cover-val">CryptoChainTrace &middot; cryptochaintrace.replit.app</span>
    <span class="cover-label">Classification:</span>
    <span class="cover-val">Confidential — Law Enforcement / Investigative Reference</span>
  </div>
</div>

<div class="report">${body}</div>

<script>
  window.addEventListener('load', function () {
    setTimeout(function () { window.print(); }, 300);
  });
</script>
</body>
</html>`;

  w.document.write(html);
  w.document.close();
}

export function exportAsJson(filename: string, data: unknown): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function reportFilename(title: string, ext: "pdf" | "json"): string {
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/, "");
  return `${slug}-${dateStr}.${ext}`;
}
